name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # runs once a day at midnight
  workflow_dispatch:      # allows manual runs from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          # Replace 'anmolp1' with your exact GitHub username, if different
          github_user_name: anmolp1  
        env:
          # Required to allow the action to fetch your contributions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy the generated SVG
        run: |
          mkdir -p dist
          cp snk/svg/* dist/

      - name: Commit updated snake to the repo
        uses: EndBug/add-and-commit@v9
        with:
          add: "dist/*.svg"
          message: "Update snake.svg"
          author_name: "GitHub Actions"
          author_email: "github-actions@github.com"
