name: Generate Snake

on:
  schedule:
    - cron: '*/15 * * * *'      # Runs every 15 mins
  workflow_dispatch:          # Allows manual trigger in the Actions tab

permissions:
  contents: write             # Required so we can commit the generated files back

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk@v3.3.0
        with:
          # Use your GitHub username (case-insensitive) here:
          github_user_name: anmolp1
          # Optional: if the default actions token doesn't work, uncomment:
          # github_token: ${{ secrets.GITHUB_TOKEN }}

          # 'outputs' is where you list each file you want generated (one per line).
          # Query params let you customize colors, theme, etc.
          outputs: |
            dark.svg?palette=github-dark&color_snake=blue

      - name: Move generated files to dist folder
        run: |
          mkdir -p dist
          mv *.svg dist/ || true
          mv *.gif dist/ || true

      - name: Commit updated snake files
        uses: EndBug/add-and-commit@v9
        with:
          add: "dist/*"
          message: "Update snake files"
          author_name: "GitHub Actions"
          author_email: "github-actions@github.com"
