name: Generate Snake

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write  # Ensures we can push files back to the repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          # Replace 'anmolp1' with your exact GitHub username if needed
          github_user_name: anmolp1
        env:
          # Provided automatically by GitHub, no need to set a custom secret
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy the generated SVG
        run: |
          mkdir -p dist
          cp snk/svg/* dist/

      - name: Commit updated snake to the repo
        uses: EndBug/add-and-commit@v9
        with:
          add: "dist/*.svg"
          message: "Update snake.svg"
          author_name: "GitHub Actions"
          author_email: "github-actions@github.com"
