name: Generate Snake

# Runs daily and also manually
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          # Use your GitHub username here
          github_user_name: anmolp1

          # Where to put the generated files
          output_path: dist

          # We specifically want a snake.svg
          output_snake: snake.svg

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "dist/snake.svg"
          message: "Update snake.svg"
          author_name: GitHub Actions
          author_email: github-actions@github.com
